### ISSUE TITLE
Configuration for IdentityServer4 projects

### ISSUE THREAD

**Issue by justSteve** [hbiarge/Acheve.Authentication.Events#1]
Greetings -- I'm interested in understanding how to integrate this package with a Blazor/.Core app that's using IdentityServer for authentication. Hoping you can take a look at the [Startup.cs](https://github.com/enkodellc/blazorboilerplate/blob/restructure/src/BlazorBoilerplate.Server/Startup.cs) and share thoughts?

**Comment by hbiarge** [comment]
Just add the NuGet package and add the `.UseLogEvents` method in the `AuthenticationBuilder` (line 230 in your sample)

**Comment by justSteve** [comment]
Apologies for my mental density... I believe we are talking about how the `authBuilder` value is being constructed. This code block right?
>var authBuilder = services.AddAuthentication(options => 
>{ 
>    options.DefaultScheme = IdentityServerAuthenticationDefaults.AuthenticationScheme; 
>}) 
>.AddIdentityServerAuthentication(options => 
>{ 
>    options.Authority = authAuthority; 
>    options.SupportedTokens = SupportedTokens.Jwt; 
>    options.RequireHttpsMetadata = _environment.IsProduction() ? true : false; 
>    options.ApiName = IdentityServerConfig.ApiName; 
>});


Intellisense insists that .`UseLogEvents ` cannot be added anywhere in that block.


thx

**Comment by hbiarge** [comment]
Yes. You can call the `UseLogEvents` method before calling `AddIdentityServerAuthentication`.
Review the `Startup.cs` in the Samples folder: https://github.com/hbiarge/Acheve.Authentication.Events/blob/65bc8b9fc96d6731c76b9b85fcce242b02445333/samples/Sample/Startup.cs#L37

**Comment by justSteve** [comment]
I found a missing `using `statement that resolved it. Thanks much!
