### ISSUE TITLE
Which version SDK is required?

### ISSUE THREAD

**Issue by justSteve** [hbiarge/Acheve.Authentication.Events#9]
My local repo is up-to-date but attempting to open your solution the project will not load:

> ...\src\Acheve.Authentication.Events\Acheve.Authentication.Events.csproj : error  : The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found.

My CLI shows this list of SDKs present -- I've tried to re-install 3.0.103 -- the installer says it's there but the list doesn't show it. Is 3.0.103 required? Any other thoughts? thx!

```
Acheve.Authentication.Events>dotnet --list-sdks
2.1.502 [C:\Program Files\dotnet\sdk]
2.1.503 [C:\Program Files\dotnet\sdk]
2.1.507 [C:\Program Files\dotnet\sdk]
2.1.602 [C:\Program Files\dotnet\sdk]
2.1.700 [C:\Program Files\dotnet\sdk]
3.1.101 [C:\Program Files\dotnet\sdk]
3.1.102 [C:\Program Files\dotnet\sdk]
```

**Comment by hbiarge** [comment]
Hi @justSteve,
You can view the required SDK version in the global.json file in the root of the repo: https://github.com/hbiarge/Acheve.Authentication.Events/blob/master/global.json
